# install_node.ps1 — Set up a secondary computer as a Corvus execution node.
# Run as Administrator on the secondary computer.
#
# Usage:
#   .\install_node.ps1 -NodeId node2 -MainDesktopIp 192.168.1.100
#
# Optional:
#   -RedisPort     (default 6380)
#   -Capabilities  (default "humanizer,capture,uia,browser,cdp,dom")
#   -InstallDir    (default D:\cb-node)

param(
    [Parameter(Mandatory=$true)]
    [string]$NodeId,

    [Parameter(Mandatory=$true)]
    [string]$MainDesktopIp,

    [int]$RedisPort = 6380,

    [string]$Capabilities = "humanizer,capture,uia,browser,cdp,dom",

    [string]$InstallDir = "D:\cb-node",

    [string]$PythonExe = "C:\Python314\python.exe"
)

$ErrorActionPreference = "Stop"

Write-Host ""
Write-Host "Corvus Node Installer" -ForegroundColor Cyan
Write-Host "  Node ID:       $NodeId"
Write-Host "  Main Desktop:  $MainDesktopIp`:$RedisPort"
Write-Host "  Install Dir:   $InstallDir"
Write-Host "  Capabilities:  $Capabilities"
Write-Host ""

# ── 1. Clone or pull repo ─────────────────────────────────────────────────────
if (-not (Test-Path $InstallDir)) {
    Write-Host "[1/5] Cloning repository..." -ForegroundColor Yellow
    git clone https://github.com/nibrah3/Corvus_Careebridge.git $InstallDir
} else {
    Write-Host "[1/5] Updating repository..." -ForegroundColor Yellow
    Push-Location $InstallDir; git pull; Pop-Location
}

# ── 2. Install Python dependencies ────────────────────────────────────────────
Write-Host "[2/5] Installing Python dependencies..." -ForegroundColor Yellow
& $PythonExe -m pip install --upgrade pip --quiet
& $PythonExe -m pip install -r "$InstallDir\requirements.txt" --quiet

# ── 3. Write .env ─────────────────────────────────────────────────────────────
Write-Host "[3/5] Configuring .env..." -ForegroundColor Yellow
Write-Host "      (Copy these values from the main desktop's E:\Corvus_Careebridge\.env)"
Write-Host ""

$TelegramToken  = Read-Host "  Telegram bot token"
$TelegramChatId = Read-Host "  Telegram admin chat ID"
$OpenRouterKey  = Read-Host "  OpenRouter API key"
$GeminiKey      = Read-Host "  Gemini API key (leave blank if unused)"

$EnvContent = @"
# Corvus Node: $NodeId
# Generated by install_node.ps1 on $(Get-Date -Format 'yyyy-MM-dd')

OPENROUTER_API_KEY=$OpenRouterKey
OPENROUTER_BASE_URL=https://openrouter.ai/api/v1
OPENROUTER_MODEL_WORKHORSE=anthropic/claude-sonnet-4-6
GEMINI_API_KEY=$GeminiKey
TELEGRAM_BOT_TOKEN=$TelegramToken
TELEGRAM_ADMIN_CHAT_ID=$TelegramChatId

# Point at the main desktop's Redis (direct LAN — no SSH tunnel needed)
REDIS_HOST=$MainDesktopIp
REDIS_PORT=$RedisPort

NODE_ID=$NodeId
NODE_CAPABILITIES=$Capabilities
TASK_TIMEOUT_SECONDS=3600
MAX_STEPS=50
"@
$EnvContent | Out-File -FilePath "$InstallDir\.env" -Encoding utf8
Write-Host "  .env written." -ForegroundColor Green

# ── 4. Write start_node.ps1 ───────────────────────────────────────────────────
Write-Host "[4/5] Writing start_node.ps1..." -ForegroundColor Yellow

$StartScript = "$InstallDir\scripts\start_node.ps1"
$StartContent = @"
# start_node.ps1 — Start execution MCPs + node agent on $NodeId.
# Run at login or from Task Scheduler.

`$PythonExe = "$PythonExe"
`$Base       = "$InstallDir"

# Load .env
Get-Content "`$Base\.env" | ForEach-Object {
    if (`$_ -match '^([^#=]+)=(.*)$') {
        `$k = `$Matches[1].Trim(); `$v = `$Matches[2].Trim()
        [System.Environment]::SetEnvironmentVariable(`$k, `$v, 'Process')
    }
}

# Execution MCPs only (no VPS/schools/answer MCPs — those live on the main desktop)
`$mcps = @(
    @{ mod = "humanizer_mcp.server"; port = 8701 },
    @{ mod = "capture_mcp.server";   port = 8702 },
    @{ mod = "uia_mcp.server";       port = 8703 },
    @{ mod = "browser_mcp.server";   port = 8704 },
    @{ mod = "dom_mcp.server";       port = 8710 },
    @{ mod = "cdp_mcp.server";       port = 8712 }
)

foreach (`$m in `$mcps) {
    Write-Host "Starting `$(`$m.mod) on `$(`$m.port)..."
    Start-Process `$PythonExe ``
        -ArgumentList "-m `$(`$m.mod) --http `$(`$m.port)" ``
        -WorkingDirectory `$Base ``
        -WindowStyle Minimized
    Start-Sleep -Milliseconds 600
}

Write-Host "Starting node agent: $NodeId"
& `$PythonExe "`$Base\scripts\node_agent.py" --node-id "$NodeId" --capabilities "$Capabilities"
"@
$StartContent | Out-File -FilePath $StartScript -Encoding utf8

# ── 5. Register firewall rule (allow Redis access from this node) ──────────────
Write-Host "[5/5] Note: ensure Redis port $RedisPort is reachable from $NodeId to $MainDesktopIp"
Write-Host "      On the main desktop, run if needed:"
Write-Host "      netsh advfirewall firewall add rule name='Corvus Redis' dir=in action=allow protocol=TCP localport=$RedisPort"
Write-Host ""

Write-Host "Installation complete!" -ForegroundColor Green
Write-Host ""
Write-Host "To start this node:" -ForegroundColor Cyan
Write-Host "  powershell $StartScript"
Write-Host ""
Write-Host "To auto-start at login, add to Task Scheduler:"
Write-Host "  Action: powershell.exe -WindowStyle Hidden -File `"$StartScript`""
Write-Host "  Trigger: At log on"
